/* ==========================================================
   LumaCart — Product Data
   All product information lives here. Every other script
   reads from this single source of truth.
   ========================================================== */

const PRODUCTS = [
  {
    id: 1,
    name: "Classic Oversized Shirt",
    category: "Fashion",
    price: 1299,
    originalPrice: 1799,
    description: "A relaxed, oversized cotton shirt cut for effortless everyday wear. Breathable fabric with a soft brushed finish.",
    rating: 4.5,
    reviews: 128,
    badge: "Sale",
    emoji: "👕",
    isNew: false,
    isBestSeller: true
  },
  {
    id: 2,
    name: "Minimal Leather Sneakers",
    category: "Shoes",
    price: 3499,
    originalPrice: 4299,
    description: "Handcrafted leather sneakers with a clean silhouette. Designed to pair effortlessly with almost anything.",
    rating: 4.7,
    reviews: 214,
    badge: "Bestseller",
    emoji: "👟",
    isNew: false,
    isBestSeller: true
  },
  {
    id: 3,
    name: "Everyday Tote Bag",
    category: "Bags",
    price: 1899,
    originalPrice: 2399,
    description: "A spacious canvas tote built for daily errands, work commutes and weekend trips alike.",
    rating: 4.4,
    reviews: 96,
    badge: "New",
    emoji: "👜",
    isNew: true,
    isBestSeller: false
  },
  {
    id: 4,
    name: "Heritage Watch",
    category: "Watches",
    price: 5499,
    originalPrice: 6999,
    description: "A timeless analog watch with a stainless steel case and genuine leather strap.",
    rating: 4.8,
    reviews: 301,
    badge: "Bestseller",
    emoji: "⌚",
    isNew: false,
    isBestSeller: true
  },
  {
    id: 5,
    name: "Wireless Headphones",
    category: "Electronics",
    price: 2999,
    originalPrice: 3999,
    description: "Over-ear wireless headphones with rich sound, plush cushioning and a 30-hour battery life.",
    rating: 4.6,
    reviews: 189,
    badge: "Sale",
    emoji: "🎧",
    isNew: false,
    isBestSeller: true
  },
  {
    id: 6,
    name: "Ceramic Desk Lamp",
    category: "Home & Living",
    price: 2199,
    originalPrice: 2699,
    description: "A soft-glow ceramic desk lamp that brings warmth and calm to any workspace.",
    rating: 4.3,
    reviews: 64,
    badge: "New",
    emoji: "💡",
    isNew: true,
    isBestSeller: false
  },
  {
    id: 7,
    name: "Essential Hoodie",
    category: "Fashion",
    price: 1799,
    originalPrice: 2299,
    description: "A midweight fleece hoodie built for comfort with a clean, minimal silhouette.",
    rating: 4.5,
    reviews: 152,
    badge: "Bestseller",
    emoji: "🧥",
    isNew: false,
    isBestSeller: true
  },
  {
    id: 8,
    name: "Canvas Backpack",
    category: "Bags",
    price: 2599,
    originalPrice: 3199,
    description: "A durable canvas backpack with padded compartments for daily commuting and travel.",
    rating: 4.4,
    reviews: 87,
    badge: "Sale",
    emoji: "🎒",
    isNew: false,
    isBestSeller: false
  },
  {
    id: 9,
    name: "Minimal Wallet",
    category: "Accessories",
    price: 899,
    originalPrice: 1199,
    description: "A slim, full-grain leather wallet designed to carry only what you need.",
    rating: 4.6,
    reviews: 143,
    badge: "Bestseller",
    emoji: "👛",
    isNew: false,
    isBestSeller: true
  },
  {
    id: 10,
    name: "Running Shoes",
    category: "Shoes",
    price: 3299,
    originalPrice: 3999,
    description: "Lightweight performance running shoes with responsive cushioning for daily miles.",
    rating: 4.5,
    reviews: 176,
    badge: "New",
    emoji: "👟",
    isNew: true,
    isBestSeller: false
  },
  {
    id: 11,
    name: "Skincare Essentials Kit",
    category: "Beauty",
    price: 1599,
    originalPrice: 1999,
    description: "A gentle three-step skincare kit with cleanser, serum and moisturizer for daily routines.",
    rating: 4.7,
    reviews: 210,
    badge: "Bestseller",
    emoji: "🧴",
    isNew: false,
    isBestSeller: true
  },
  {
    id: 12,
    name: "Smart Desk Organizer",
    category: "Home & Living",
    price: 1299,
    originalPrice: 1599,
    description: "A modular desk organizer with dedicated slots for stationery, cables and everyday essentials.",
    rating: 4.2,
    reviews: 58,
    badge: "New",
    emoji: "🗂️",
    isNew: true,
    isBestSeller: false
  },
  {
    id: 13,
    name: "Sunglasses",
    category: "Accessories",
    price: 1099,
    originalPrice: 1499,
    description: "Polarized sunglasses with a lightweight acetate frame and UV400 protection.",
    rating: 4.3,
    reviews: 92,
    badge: "Sale",
    emoji: "🕶️",
    isNew: false,
    isBestSeller: false
  },
  {
    id: 14,
    name: "Casual Shirt",
    category: "Fashion",
    price: 1099,
    originalPrice: 1399,
    description: "A breathable everyday shirt in a soft cotton blend, tailored for a relaxed fit.",
    rating: 4.2,
    reviews: 74,
    badge: "",
    emoji: "👔",
    isNew: false,
    isBestSeller: false
  },
  {
    id: 15,
    name: "Premium Backpack",
    category: "Bags",
    price: 3199,
    originalPrice: 3999,
    description: "A refined leather-trimmed backpack with a padded laptop sleeve and premium hardware.",
    rating: 4.7,
    reviews: 121,
    badge: "Limited",
    emoji: "🎒",
    isNew: false,
    isBestSeller: true
  },
  {
    id: 16,
    name: "Bluetooth Speaker",
    category: "Electronics",
    price: 1899,
    originalPrice: 2399,
    description: "A compact wireless speaker with immersive sound and a 12-hour battery life.",
    rating: 4.4,
    reviews: 133,
    badge: "Sale",
    emoji: "🔊",
    isNew: false,
    isBestSeller: false
  },
  {
    id: 17,
    name: "Linen Cushion Set",
    category: "Home & Living",
    price: 1499,
    originalPrice: 1899,
    description: "A set of two linen cushion covers in earthy tones, made to soften any living space.",
    rating: 4.5,
    reviews: 46,
    badge: "New",
    emoji: "🛋️",
    isNew: true,
    isBestSeller: false
  },
  {
    id: 18,
    name: "Analog Watch",
    category: "Watches",
    price: 2799,
    originalPrice: 3499,
    description: "A minimal analog watch with a slim case and interchangeable strap.",
    rating: 4.3,
    reviews: 68,
    badge: "",
    emoji: "⌚",
    isNew: false,
    isBestSeller: false
  },
  {
    id: 19,
    name: "Crossbody Bag",
    category: "Bags",
    price: 1699,
    originalPrice: 2199,
    description: "A compact crossbody bag with an adjustable strap, made for hands-free days.",
    rating: 4.4,
    reviews: 79,
    badge: "New",
    emoji: "👜",
    isNew: true,
    isBestSeller: false
  },
  {
    id: 20,
    name: "Travel Organizer",
    category: "Accessories",
    price: 999,
    originalPrice: 1299,
    description: "A compact pouch system for organizing cables, chargers and travel essentials.",
    rating: 4.2,
    reviews: 51,
    badge: "",
    emoji: "🧳",
    isNew: false,
    isBestSeller: false
  },
  {
    id: 21,
    name: "Desk Clock",
    category: "Home & Living",
    price: 799,
    originalPrice: 999,
    description: "A quiet-sweep desk clock with a warm wood-toned finish.",
    rating: 4.1,
    reviews: 33,
    badge: "",
    emoji: "🕰️",
    isNew: false,
    isBestSeller: false
  },
  {
    id: 22,
    name: "Water Bottle",
    category: "Accessories",
    price: 599,
    originalPrice: 799,
    description: "An insulated stainless steel bottle that keeps drinks cold for 24 hours.",
    rating: 4.6,
    reviews: 167,
    badge: "Bestseller",
    emoji: "🍶",
    isNew: false,
    isBestSeller: true
  },
  {
    id: 23,
    name: "Casual Sneakers",
    category: "Shoes",
    price: 2499,
    originalPrice: 2999,
    description: "Everyday canvas sneakers with a cushioned sole and a low-profile design.",
    rating: 4.3,
    reviews: 88,
    badge: "Sale",
    emoji: "👟",
    isNew: false,
    isBestSeller: false
  },
  {
    id: 24,
    name: "Essential Cap",
    category: "Accessories",
    price: 599,
    originalPrice: 799,
    description: "A structured cotton cap with an adjustable strap, finished with minimal branding.",
    rating: 4.0,
    reviews: 41,
    badge: "New",
    emoji: "🧢",
    isNew: true,
    isBestSeller: false
  }
];

const CATEGORIES = [
  { name: "Fashion", emoji: "👕", description: "Everyday wardrobe staples" },
  { name: "Shoes", emoji: "👟", description: "Sneakers, running & more" },
  { name: "Bags", emoji: "👜", description: "Totes, backpacks & pouches" },
  { name: "Watches", emoji: "⌚", description: "Timeless & modern pieces" },
  { name: "Accessories", emoji: "🕶️", description: "The finishing details" },
  { name: "Beauty", emoji: "🧴", description: "Simple daily rituals" },
  { name: "Home & Living", emoji: "🛋️", description: "Calm, curated spaces" },
  { name: "Electronics", emoji: "🎧", description: "Everyday essentials" }
];

/* Helper: fetch a single product by id (string or number safe) */
function getProductById(id) {
  const numId = Number(id);
  return PRODUCTS.find((p) => p.id === numId);
}
